services:
  web:
    image: apache2
    container_name: ak4-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - appnet
  db:
    image: mariadb
    container_name: ak4-db
    volumes:
      - varehusdb:/var/lib/mysql
    environment:
      db_root_password: root123
      db_user: appuser
      db_password: apppass
      db_name: varehusdb
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet: {}

volumes:
  varehusdb: